name: 'NoChainTNT'
version: '1.1.0'
api-version: 1.19
main: com.project610.NoChainTNT.NoChainTNT
commands:
  maxtntchain:
    description: Set how many times TNT can chain-explode
    permission: nochaintnt.edit
    permission-message: I'm afraid I can't let you do that
permissions:
  nochaintnt.edit:
    description: Allow editing NoChainTNT settings
    default: op
